apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emaram/api-helm-chart.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true